config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :coupons
  resources :movies
  resources :screens
  resources :theatres
  devise_for :users
  
  resources :theatres do
    resources :screens
  end
  resources :screens do
    resource :movies
  end
  resources :movies do
    resources :coupons
  end
  resources :movies do
    resources :bookings    
  end
  root 'home#index'

end

app/models/theatre.rb
class Theatre < ApplicationRecord
    has_many :screens
    validates :name, presence: true
    validates :location, presence: true
end

app/controllers/theatres_controller.rb
class TheatresController < ApplicationController
  before_action :set_theatre, only: %i[ show edit update destroy ]

  # GET /theatres or /theatres.json
  def index
    @theatres = Theatre.all
  end

  # GET /theatres/1 or /theatres/1.json
  def show
  end

  # GET /theatres/new
  def new
    @theatre = Theatre.new
  end

  # GET /theatres/1/edit
  def edit
  end

  # POST /theatres or /theatres.json
  def create
    @theatre = Theatre.new(theatre_params)

      if @theatre.save
        redirect_to theatres_path
      else
        
      end
    
  end

  # PATCH/PUT /theatres/1 or /theatres/1.json
  def update
    respond_to do |format|
      if @theatre.update(theatre_params)
        format.html { redirect_to @theatre, notice: "Theatre was successfully updated." }
        format.json { render :show, status: :ok, location: @theatre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @theatre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theatres/1 or /theatres/1.json
  def destroy
    @theatre.destroy
    respond_to do |format|
      format.html { redirect_to theatres_url, notice: "Theatre was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theatre
      @theatre = Theatre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def theatre_params
      params.require(:theatre).permit(:name, :location)
    end
end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/views/theatres/_form.html.erb
<%= form_with(model: theatre, local: true) do |form| %>
  <% if theatre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(theatre.errors.count, "error") %> prohibited this theatre from being saved:</h2>

      <ul>
      <% theatre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/theatres/edit.html.erb
<h1>Editing Theatre</h1>

<%= render 'form', theatre: @theatre %>

<%= link_to 'Show', @theatre %> |
<%= link_to 'Back', theatres_path %>

app/views/theatres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Theatres</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @theatres.each do |theatre| %>
      <tr>
        <td><%= theatre.name %></td>
        <td><%= theatre.location %></td>
        <%if current_user.type = "Admin"%>
        <td><%= link_to 'Show', theatre %></td>
        <td><%= link_to 'Edit', edit_theatre_path(theatre) %></td>
        <td><%= link_to 'Destroy', theatre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Add Screen',  new_theatre_screen_path(theatre)%></td>
        <%else%>
        <td><%= link_to 'Select Theatre', screens_path(theatre)%>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
 <%if current_user.type = "Admin"%>
    <%= link_to 'New Theatre', new_theatre_path %>
<%end%>

app/views/theatres/new.html.erb
<h1>New Theatre</h1>

<%= render 'form', theatre: @theatre %>

<%= link_to 'Back', theatres_path %>

app/views/theatres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @theatre.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @theatre.location %>
</p>

<%= link_to 'Edit', edit_theatre_path(@theatre) %> |

<%= link_to 'Add Screen', new_theatre_screen_path(@theatre) %> |
<%= link_to 'Back', theatres_path %>