config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :coupons
  resources :movies
  resources :screens
  resources :theatres
  devise_for :users
  
  resources :theatres do
    resources :screens
  end
  resources :screens do
    resource :movies
  end
  resources :movies do
    resources :coupons
  end
  resources :movies do
    resources :bookings    
  end
  root 'home#index'

end

app/models/screen.rb
class Screen < ApplicationRecord
  belongs_to :theatre
  has_many :movies
  has_many :coupons
  # validates :date, presence: true, format: { with: /^\d{2}-\d{2}-\d{4}$/, message: "Maintain DD-MM-YYYY format"}
  validates :fee, presence: true
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController
  before_action :set_screen, only: %i[ show edit update destroy ]
  # GET /screens or /screens.json
  def index
    @screens = Screen.all
  end

  # GET /screens/1 or /screens/1.json
  def show
  end

  # GET /screens/new
  def new
    @theatre = Theatre.find(params[:theatre_id])
    @screen = Screen.new
  end

  # GET /screens/1/edit
  def edit
  end

  # POST /screens or /screens.json
  def create

   @theatre = Theatre.find(params[:theatre_id])
   @screen = @theatre.screens.create(screen_params)

      if @screen.save
        redirect_to screens_path
      else
        
      end
    
  end

  # PATCH/PUT /screens/1 or /screens/1.json
  def update
    respond_to do |format|
      if @screen.update(screen_params)
        format.html { redirect_to @screen, notice: "Screen was successfully updated." }
        format.json { render :show, status: :ok, location: @screen }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @screen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screens/1 or /screens/1.json
  def destroy
    @screen.destroy
    respond_to do |format|
      format.html { redirect_to screens_url, notice: "Screen was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_screen
      @screen = Screen.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def screen_params
      params.require(:screen).permit(:date, :fee, :seat_id, :timing_id)
    end
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/views/screens/_form.html.erb
<%= form_for([ @theatre, @screen]) do |form| %>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date, placeholder: 'dd-mm-yyyy' %>
  </div>

  <div class="field">
    <%= form.label :fee %>
    <%= form.number_field :fee %>
  </div>

  <div class="field">
    <%= form.hidden_field :theatre_id %>
  </div>

  <div class="field">
    <%= form.collection_select :timing_id, Timing.all, :id, :time %>
  </div>

  <div class="field">
    <%= form.collection_select :seat_id, Seat.all, :id, :seat_count %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/screens/edit.html.erb
<h1>Editing Screen</h1>

<%= render 'form', screen: @screen %>

<%= link_to 'Show', @screen %> |
<%= link_to 'Back', screens_path %>

app/views/screens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Screens</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Fee</th>
      <th>Theatre</th>
      <th>Seat count</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @screens.each do |screen| %>
      <tr>
        <td><%= screen.date %></td>
        <td><%= screen.fee %></td>
        <td><%= screen.theatre.name %></td>
        <td><%= Seat.find(screen.seat_id).seat_count %></td>
        <td><%= Timing.find(screen.timing_id).time %></td>
        <%if current_user.type == "Admin"%>
        <td><%= link_to 'Show', screen %></td>
        <td><%= link_to 'Destroy', screen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Add Movie', new_screen_movies_path(screen)%></td>
        <%else%>
        <td><%= link_to 'Select Screen', movies_path(screen)%>
        <%end%>
      </tr>

    <% end %>
  </tbody>
</table>
<br>

app/views/screens/new.html.erb
<h1>New Screen</h1>

<%= render 'form', screen: @screen %>

<%= link_to 'Back', screens_path %>

app/views/screens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @screen.date %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @screen.fee %>
</p>

<p>
  <strong>Theatre:</strong>
  <%= @screen.theatre %>
</p>

<p>
  <strong>Seat count:</strong>
  <%= @screen.seat_count %>
</p>

<p>
  <strong>Time:</strong>
  <%= @screen.time %>
</p>

<%= link_to 'Edit', edit_screen_path(@screen) %> |
<%= link_to 'Back', screens_path %>