config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :coupons
  resources :movies
  resources :screens
  resources :theatres
  devise_for :users
  
  resources :theatres do
    resources :screens
  end
  resources :screens do
    resource :movies
  end
  resources :movies do
    resources :coupons
  end
  resources :movies do
    resources :bookings    
  end
  root 'home#index'

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.order(id: :desc)
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    @movie = Movie.find(params[:movie_id])

  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @movie = Movie.find(params[:movie_id])
    @booking = @movie.bookings.create(booking_params)
    @booking.user_id = current_user.id
    @coupon = @booking.coupon_code
    @seat_count = @booking.seat_count
    @match = Coupon.find_by(code: @coupon)
    @screen_fee = @booking.movie.screen.fee
    @fee = @seat_count * @screen_fee
    if @match
      @percentage = @match.percentage
      @fee = @fee - ((@fee * @percentage)/100) 
      # @match.coupon_count = @match.coupon_count - 1     
    end
    @booking.total_fee = @fee
      if @booking.save
        redirect_to root_path
      else
        # redirect_to root_path
      end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy
      redirect_to root_path
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:coupon_code, :user_id, :movie_id, :total_fee, :seat_count)
    end
    
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for([@movie, @booking]) do |form| %>
  
  <div class="field">
    <%= form.label :coupon_code %>
    <%= form.text_field :coupon_code, placeholder: 'Enter Your Coupon Code' %>
  </div>

  <div class="field">
    <%= form.label :seat_count %>
    <%= form.number_field :seat_count %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Coupon code</th>
      <th>User</th>
      <th>Movie</th>
      <th>Total fee</th>
      <th>Seat count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.coupon_code %></td>
        <td><%= booking.user %></td>
        <td><%= booking.movie %></td>
        <td><%= booking.total_fee %></td>
        <td><%= booking.seat_count %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', theatres_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Coupon code:</strong>
  <%= @booking.coupon_code %>
</p>

<p>
  <strong>User:</strong>
  <%= @booking.user %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @booking.movie %>
</p>

<p>
  <strong>Total fee:</strong>
  <%= @booking.total_fee %>
</p>

<p>
  <strong>Seat count:</strong>
  <%= @booking.seat_count %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>