config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :coupons
  resources :movies
  resources :screens
  resources :theatres
  devise_for :users
  
  resources :theatres do
    resources :screens
  end
  resources :screens do
    resource :movies
  end
  resources :movies do
    resources :coupons
  end
  resources :movies do
    resources :bookings    
  end
  root 'home#index'

end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :movie
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :set_coupon, only: %i[ show edit update destroy ]

  # GET /coupons or /coupons.json
  def index
    @coupons = Coupon.all
  end

  # GET /coupons/1 or /coupons/1.json
  def show
  end

  # GET /coupons/new
  def new
    @coupon = Coupon.new
    @movie = Movie.find(params[:movie_id])
  end

  # GET /coupons/1/edit
  def edit
  end

  # POST /coupons or /coupons.json
  def create
    @movie = Movie.find(params[:movie_id])
    @coupon = @movie.coupons.create(coupon_params)
      if @coupon.save
        redirect_to coupons_path
      else
        # redirect_to root_path
      end
    
  end

  # PATCH/PUT /coupons/1 or /coupons/1.json
  def update
    respond_to do |format|
      if @coupon.update(coupon_params)
        format.html { redirect_to @coupon, notice: "Coupon was successfully updated." }
        format.json { render :show, status: :ok, location: @coupon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coupons/1 or /coupons/1.json
  def destroy
    @coupon.destroy
    respond_to do |format|
      format.html { redirect_to coupons_url, notice: "Coupon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coupon
      @coupon = Coupon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coupon_params
      params.require(:coupon).permit(:code, :coupon_count, :percentage)
    end
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/views/coupons/_form.html.erb
<%= form_for([@movie, @coupon]) do |form| %>
  
  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :coupon_count %>
    <%= form.number_field :coupon_count %>
  </div>

  <div class="field">
    <%= form.label :percentage %>
    <%= form.number_field :percentage %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coupons/edit.html.erb
<h1>Editing Coupon</h1>

<%= render 'form', coupon: @coupon %>

<%= link_to 'Show', @coupon %> |
<%= link_to 'Back', coupons_path %>

app/views/coupons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coupons</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Coupon count</th>
      <th>Percentage</th>
      <th>Movie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coupons.each do |coupon| %>
      <tr>
        <td><%= coupon.code %></td>
        <td><%= coupon.coupon_count %></td>
        <td><%= coupon.percentage %></td>
        <td><%= coupon.movie.name %></td>
        <%if current_user.type == "Admin"%>
        <td><%= link_to 'Show', coupon %></td>
        <td><%= link_to 'Destroy', coupon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/coupons/new.html.erb
<h1>New Coupon</h1>

<%= render 'form', coupon: @coupon %>

<%= link_to 'Back', coupons_path %>

app/views/coupons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @coupon.code %>
</p>

<p>
  <strong>Coupon count:</strong>
  <%= @coupon.coupon_count %>
</p>

<p>
  <strong>Percentage:</strong>
  <%= @coupon.percentage %>
</p>

<p>
  <strong>Screen:</strong>
  <%= @coupon.screen %>
</p>

<%= link_to 'Edit', edit_coupon_path(@coupon) %> |
<%= link_to 'Back', coupons_path %>